### PR TITLE
noColor and fixedEnergy added

### PR DESCRIPTION
**Pull request by BernhardEgger**
This adds two new options to the illumination prior.
The prior generates various illumination with diverse colour. Those variation might be to wild for some applications. 
- A new switch "no-color" allows to remove all color variation and returns the average over all colour channels per illumination component.
- The first component of Spherical Harmonics is changing the ambient part of the illumination. This variation might also be not necessary for some applications. Therefore a new switch "fixAmbient" allows to set this value explicitly to a value "fixAmbientValue".
Both switches allow to still use the empirical distribution of the Basel Illumination Prior but allow to limit its flexibility

### CODE REVIEW

**Review by Andreas-Forster — COMMENTED** [review]
In general I agree to merge this PR as it looks reasonable.

But what is about backward compatibility of the configuration files? It seems that this will break all older config files? The reader has no default arguments for the newly added fields?

If we decide to break this backward compatibility maybe we should start a "guide" in the README that explains which fields to add for the different releases or versions. What do you think?

**Comment by BernhardEgger** [comment]
Yes it breaks the config file.
Every change so far did this.
Since example config files are part of the repository there is always a config file that works with the corresponding version.
The releases also contain the corresponding config files - so I would argue that this should work for everybody.

**Review by Andreas-Forster — APPROVED** [review]
That is true that one can look at the diff between the versions of the provided config files. But it would be more user-friendly to see it directly in the README.

**Comment by BernhardEgger** [comment]
What about adding something like this to the readme?:
"Config files are not compatible between versions. When new features are added this usually leads to additional fields in the respective config file. However, the example config files are part of the repository and we keep them running when updating - those can be used as starting point or as clue to adapt your config file."
I really think it does not make sense to try to list those changes - it would also be very hard to read/implement them. The error messages when a value in the used config file are much more supportive when changing between versions.

**Comment by Andreas-Forster** [comment]
I think this information does not help much. But maybe it is really the best thing not to document it. Otherwise, we would describe how to go to the immediate next version, but when you skip a version you already have to combine two updates. A diff in the git history can show you a more appropriate way how to update your configs.

So as indicated I am fine with merging without a change to the README.

**Comment by AdamKortylewski** [comment]
I think we run into the general problem that the config files get filled with information that is actually irrelevant for the audience that this project was initially made for (Deep Learning for facial image analysis) and is more and more filled with things that are useful but actually might not be used by many people in the future. What about using two config files? One general file that offers access to the most important parameters and one advanced file that allows for a more detailed configuration?

**Comment by BernhardEgger** [comment]
You are right - it is getting filled. So far I think it should still be possible to read through all of it in reasonable time. My concern with what you are proposing is the following:
Indeed most of the people will only use a subset of those configurations. I however think that that subset might not be always the same - so there will be no set of common agreed important parameters.
It should be reasonable to spend some time reading through all the possibilities of configuration when you want to use it - and I think we try to kept the example configuration such that it is somehow a nice working example with only the most important parameters - the too fancy stuff is off...
Implementing your idea might make it more complicated instead of the motivation of simplification (settings: random, controlled, randomAdvanced, controlledAdvanced with all there different configurations or switches hidden switches).

**Comment by Andreas-Forster** [comment]
I think a smart ordering within the config file could help that people see the most important options first. It might be already like this. But, they might be inspired, what else they can try out when reading all the options. Maybe there is even something they want but haven't yet thought about it. As in the provided config files the options have a default value they do not need to know every option when starting.

**Comment by BernhardEgger** [comment]
I agree that the ordering should not be too bad. I checked the ordering and from my perspective it already makes sense. I however still think that one should go through and check all the options available - and you are write, that also shows everybody what they can actually do.
In contrast to this config file, a fancy GUI would of course be cool - but most people might run it on servers - so perhaps a GUI to write the config file? I would say that the config file is at the moment to small to really profit from a GUI, but it could be an option if we realize that it grows and grows in future.
However we handle this now or in future - I think this discussion is now slightly unrelated to the original PR :)

**Comment by BernhardEgger** [comment]
Sorry - I updated this pull request 🎠 . I realized that it might be smarter to fix the energy of the Spherical Harmonics parameters instead of fixing the ambient part. Fixing the ambient term leads to very light examples since the components are additive. Fixing the energy leads to constant "strenght" of illumination. This makes much more sense in my eyes and is also slightly less hacky.

**Pull request merged**
